/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnicianRouteImport } from './routes/technician'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Api_scheduledServerRouteImport } from './routes/api/__scheduled.server'

const TechnicianRoute = TechnicianRouteImport.update({
  id: '/technician',
  path: '/technician',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Api_scheduledServerRoute = Api_scheduledServerRouteImport.update({
  id: '/api/__scheduled/server',
  path: '/api/server',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/technician': typeof TechnicianRoute
  '/api/server': typeof Api_scheduledServerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/technician': typeof TechnicianRoute
  '/api/server': typeof Api_scheduledServerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/technician': typeof TechnicianRoute
  '/api/__scheduled/server': typeof Api_scheduledServerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/technician' | '/api/server'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/technician' | '/api/server'
  id: '__root__' | '/' | '/admin' | '/technician' | '/api/__scheduled/server'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TechnicianRoute: typeof TechnicianRoute
  Api_scheduledServerRoute: typeof Api_scheduledServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technician': {
      id: '/technician'
      path: '/technician'
      fullPath: '/technician'
      preLoaderRoute: typeof TechnicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/__scheduled/server': {
      id: '/api/__scheduled/server'
      path: '/api/server'
      fullPath: '/api/server'
      preLoaderRoute: typeof Api_scheduledServerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TechnicianRoute: TechnicianRoute,
  Api_scheduledServerRoute: Api_scheduledServerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
