/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkOrdersIdRouteImport } from './routes/work-orders.$id'
import { Route as ApiHcpRevenueSyncRouteImport } from './routes/api/hcp-revenue-sync'
import { Route as ApiHcpDebugRouteImport } from './routes/api/hcp-debug'

const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersIdRoute = WorkOrdersIdRouteImport.update({
  id: '/work-orders/$id',
  path: '/work-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHcpRevenueSyncRoute = ApiHcpRevenueSyncRouteImport.update({
  id: '/api/hcp-revenue-sync',
  path: '/api/hcp-revenue-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHcpDebugRoute = ApiHcpDebugRouteImport.update({
  id: '/api/hcp-debug',
  path: '/api/hcp-debug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRoute
  '/api/hcp-debug': typeof ApiHcpDebugRoute
  '/api/hcp-revenue-sync': typeof ApiHcpRevenueSyncRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRoute
  '/api/hcp-debug': typeof ApiHcpDebugRoute
  '/api/hcp-revenue-sync': typeof ApiHcpRevenueSyncRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/revenue': typeof RevenueRoute
  '/api/hcp-debug': typeof ApiHcpDebugRoute
  '/api/hcp-revenue-sync': typeof ApiHcpRevenueSyncRoute
  '/work-orders/$id': typeof WorkOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/revenue'
    | '/api/hcp-debug'
    | '/api/hcp-revenue-sync'
    | '/work-orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/revenue'
    | '/api/hcp-debug'
    | '/api/hcp-revenue-sync'
    | '/work-orders/$id'
  id:
    | '__root__'
    | '/'
    | '/revenue'
    | '/api/hcp-debug'
    | '/api/hcp-revenue-sync'
    | '/work-orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RevenueRoute: typeof RevenueRoute
  ApiHcpDebugRoute: typeof ApiHcpDebugRoute
  ApiHcpRevenueSyncRoute: typeof ApiHcpRevenueSyncRoute
  WorkOrdersIdRoute: typeof WorkOrdersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders/$id': {
      id: '/work-orders/$id'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id'
      preLoaderRoute: typeof WorkOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hcp-revenue-sync': {
      id: '/api/hcp-revenue-sync'
      path: '/api/hcp-revenue-sync'
      fullPath: '/api/hcp-revenue-sync'
      preLoaderRoute: typeof ApiHcpRevenueSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hcp-debug': {
      id: '/api/hcp-debug'
      path: '/api/hcp-debug'
      fullPath: '/api/hcp-debug'
      preLoaderRoute: typeof ApiHcpDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RevenueRoute: RevenueRoute,
  ApiHcpDebugRoute: ApiHcpDebugRoute,
  ApiHcpRevenueSyncRoute: ApiHcpRevenueSyncRoute,
  WorkOrdersIdRoute: WorkOrdersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
